version: '3.7'
services:
  nginx:
    build: docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
  php:
    build: docker/php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html/
    command: php-fpm
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: RandomKey
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
networks:
  default:
